quassibly/novelty-app

app/models/chapter.rb
app/models/novel.rb
app/models/writing_session.rb
db/migrate/20180528123540_devise_create_users.rb
db/migrate/20180528135328_create_novels.rb
db/migrate/20180528140133_create_chapters.rb
db/migrate/20180528140350_create_writing_sessions.rb
test/models/chapter_test.rb
test/models/novel_test.rb
test/models/writing_session_test.rb

Models and validations were generated

Generated models

---

app/assets/stylesheets/pages/_edit.scss
app/controllers/pages_controller.rb
app/views/novels/edit.html.erb

temporary styling for edit page

Basic styling

---

app/controllers/novels_controller.rb
app/views/novels/edit.html.erb
app/views/shared/_random.html.erb

put the sentence generator in a modal.  can't generate a new sentence yet

Random modal

---

app/controllers/goals_controller.rb
app/controllers/novels_controller.rb
app/views/goals/new.html.erb
app/views/pages/home.html.erb
config/routes.rb

Removed nest routing of goals. 
changed goals controller slightly
form put onto homepage instead of textarea for now until we sort out JSON fetch

Link added to banner for new project

---

app/assets/stylesheets/components/_sidebar.scss
app/assets/stylesheets/pages/_edit.scss
app/views/novels/edit.html.erb

Removed border of edit-form

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_modal.scss
app/assets/stylesheets/components/_sidebar.scss
app/assets/stylesheets/pages/_edit.scss
app/views/novels/edit.html.erb
app/views/sentences/random.html.erb
app/views/shared/_random.html.erb
app/views/shared/_sidebar.html.erb

Didnt edit yet the bottom buttons because wanted to merge with Kolja.  Will make buttons pretty after the merge.

Modal styles and edit page without form action styling

---

app/views/users/show.html.erb

changed color on chart

---

app/assets/stylesheets/pages/_edit.scss

Form on edit page has a border once more. In addition, the blue outline doesn't show anymore when the textfield is selected

Added form-border and turned outline off

---

app/assets/stylesheets/components/_charts.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/pages/_show.scss
app/views/users/show.html.erb

dashboard labels and button

---

app/assets/stylesheets/pages/_home.scss
app/controllers/pages_controller.rb
app/javascript/packs/application.js
app/javascript/packs/typed.js
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
config/initializers/assets.rb
package.json
yarn.lock

I finally got the Typed.js to work. Unfortunately it's still underneath the banner, because I couldn't get it to work there just yet. It broke the styling that we added before. So that will need another look.

Implemented Typed.js on homepage

---

app/assets/stylesheets/components/_alert.scss
app/javascript/packs/application.js
app/javascript/packs/flashes.js
app/views/shared/_flashes.html.erb

Works, but quite possibly needs a rf to only run on relevant pages... Will consult a TA.

flashes styling and disappearance

---

app/controllers/novels_controller.rb

filtered by project date range.  Chart works!

---

app/controllers/novels_controller.rb
app/views/shared/_statistics.html.erb

Once we have better seeds with data from different days, we should be able to test if it works

Added todays word count to stats

---

app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_review.scss
app/views/reviews/show.html.erb
app/views/shared/_review.html.erb

definitely needs some finessing, but the basic layout is begun

basic layout for reviews page

---

app/assets/stylesheets/pages/_edit.scss
app/javascript/packs/application.js
app/javascript/packs/progress_bar.js
app/views/layouts/application.html.erb
app/views/novels/edit.html.erb
app/views/shared/_statistics.html.erb
db/schema.rb

Added progress bar and adjusted calculation for todays word count

Edit progress bar

---

app/javascript/packs/typed.js
app/views/pages/home.html.erb

shorter pause, slightly faster typing

Timing for typed.js adjusted

---

app/controllers/reviews_controller.rb
app/views/reviews/show.html.erb
app/views/shared/_review.html.erb
config/routes.rb

Review more stuff

---

app/assets/stylesheets/pages/_edit.scss
app/views/novels/edit.html.erb

The positions of the buttons still need fixing

Moving submit button

---

app/assets/stylesheets/components/_modal.scss
app/views/goals/new.html.erb
app/views/shared/_statistics.html.erb

Needs more styling with flex box

a little styling

---

app/javascript/packs/autosave.js
app/javascript/packs/flames.js
app/views/novels/edit.html.erb
app/views/shared/_flames.html.erb
app/views/shared/_random.html.erb

Party Parrot

---

app/views/layouts/application.html.erb
app/views/reviews/show.html.erb

Added a line to the meta tags which allows reading of authenticity token on forms.

Meta tag code added
